apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP