apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    app: rabbitmq
data:
  rabbitmq.conf: |
    listeners.tcp.default = 5672
    management.listener.port = 15672
    management.listener.ip = 0.0.0.0
    loopback_users = none