apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: bookstore
  labels:
    app: catalog
spec:
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP