apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-payment-svc
  labels:
    app: rabbitmq-payment
spec:
  selector:
    app: rabbitmq-payment
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP