apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP