apiVersion: v1
kind: Service
metadata:
  name: review-service
  labels:
    app: review
spec:
  selector:
    app: review
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP