apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: bookstore
  labels:
    app: cart
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP