apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app: cart
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cart-svc
  labels:
    app: rabbitmq-cart
spec:
  selector:
    app: rabbitmq-cart
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP