apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app: cart
spec:
  selector:
    app: cart
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: grpc
      protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP