apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-user-svc
  labels:
    app: rabbitmq-user
spec:
  selector:
    app: rabbitmq-user
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP